var obj =
    [
        {
            "id": 1,
            "Name": "Interacciones de estrellas y materia interestelar en Escorpio Centauro",
            "Abstract": "The interaction of the stars in the Scorpio-Centaurus OB association with the ambient interstellar medium is investigated. Large H I loops in the fourth galactic quadrant are parts of expanding shells surrounding the subgroups of the association. The energy output of the original stellar population of the subgroups is calculated. Comparison with the kinetic energy of the shells shows that the energy output of the stars in the subgroups is sufficient to form the shells. The masses of the shells are consistent with those of giant molecular clouds GMCs, suggesting that the shells consist of swept-up, original GMC material. The influence of the expanding shell around the young Upper-Scorpius subgroup on the morphology of the Ophiuchus molecular clouds is investigated. The interaction of the shell with the Ophiuchus clouds accounts for the presence of a slow shock and for the shape of the elongated dark clouds connected to the Rho Oph dense cloud. The close passage of the trajectory of the runaway star Zeta Oph by the center of the Upper-Scorpius shell, combined with the time scale of formation of the shell, strongly suggests that the star has originated in the Upper-Scorpius subgroup.",
            "Simplified": "El sistema estelar Escorpio-Centauro tiene una estrecha relación con su vecino lejano Centauro. El Telescopio Espacial Hubble ha capturado una serie de imágenes del Gran Colisionador de Hadrones (LHC) en Cern en Cern, Suiza. Se investiga la morfología de las nubes moleculares jóvenes en las Grandes Nubes de Magallanes (LMCC). ."
        },
        {
            "id": 2,
            "Name": "Soldadura explosiva de aluminio, titanio y zirconio a chapa de cobre",
            "Abstract": "The main material properties affecting the explosive weldability of a certain metal combination are the yield strength, the ductility, the density and the sonic velocity of the two metals. Successful welding of the metal combination depends mainly on the correct choice of the explosive welding parameters; i.e., the stand off distance, the weight of the explosive charge relative to the weight of the flyer plate and the detonation velocity of the explosive. Based on the measured and the handbook values of the properties of interest, the explosive welding parameters were calculated and the arrangements for the explosive welding of the Al alloy 6061-T6, titanium and zirconium to OFHC copper were determined. The relatively small sheet metal thickness (1/8\") and the fact that the thickness of the explosive layer must exceed a certain minimum value were considered during the determination of the explosive welding conditions. The results of the metallographic investigations and the measurements of the shear strength at the interface demonstrate the usefulness of these calculations to minimize the number of experimental trials.",
            "Simplified": "La soldabilidad explosiva de una determinada combinación de metales depende de una serie de factores. La soldadura explosiva de aleación de Al-T6, titanio y zirconio-T6 y cobre OFHC se ha realizado en un laboratorio en Alemania. El espesor de la capa explosiva está determinado por el espesor de la chapa. En este documento, se utilizan cálculos de elementos finitos (FE) para estimar la resistencia al corte en la interfaz entre un acero inoxidable martensítico y un acero inoxidable martensítico."
        },
        {
            "id": 3,
            "Name": "El diseño de álabes de turbomáquina utilizando el enfoque S2-S1",
            "Abstract": "The boundary conditions corresponding to the design problem when the blades being simulated by the bound vorticity distribution are presented. The 3D flow is analyzed by the two steps S2 - S1 approach. In the first step, the number of blades is supposed to be infinite, the vortex distribution is transformed into an axisymmetric one, so that the flow field can be analyzed in a meridional plane. The thickness distribution of the blade producing the flow channel striction is taken into account by the modification of metric tensor in the continuity equation. Using the meridional stream function to define the flow field, the mass conservation is satisfied automatically. The governing equation is deduced from the relation between the azimuthal component of the vorticity and the meridional velocity. The value of the azimuthal component of the vorticity is provided by the hub to shroud equilibrium condition. This step leads to the determination of the axisymmetric stream sheets as well as the approximate camber surface of the blade. In the second step, the finite number of blades is taken into account, the inverse problem corresponding to the blade to blade flow confined in each stream sheet is analyzed. The momentum equation implies that the free vortex of the absolute velocity must be tangential to the stream sheet. The governing equation for the blade to blade flow stream function is deduced from this condition. At the beginning, the upper and the lower surfaces of the blades are created from the camber surface obtained from the first step with the assigned thickness distribution. The bound vorticity distribution and the penetrating flux conservation applied on the presumed blade surface constitute the boundary conditions of the inverse problem. The detection of this flux leads to the rectification of the geometry of the blades.",
            "Simplified": "Este artículo presenta los resultados de un estudio sobre el diseño y operación de una pala de aerogenerador. En este artículo, presentamos un nuevo método para el análisis del campo de flujo de una corriente en chorro, basado en la idea de que el campo de flujo de un álabe de turbina es proporcional a su número de álabes. Se realiza un estudio numérico de la restricción del canal de flujo de un álabe de diámetro inferior a 1 mm. Este artículo presenta los resultados de un estudio numérico de la distribución de vorticidad y la conservación del flujo penetrante aplicado a la supuesta superficie del álabe."
        },
        {
            "id": 4,
            "Name": "Uso de radar terrestre para detectar el reingreso de escombros",
            "Abstract": "The velocity of the particles is required to identify the type of particles producing the ionization trails. A method of approximating the velocity of a meteor from radar data was developed. The method requires the time between the spacings of the Fresnel interference fringes, the range to the ionization trail, and the wavelength of the radar system. The orbital mechanics of the problem are evaluated, if the particles originate with the shuttle, the orbital mechanics will substantiate the relative position of the particles with the position of the shuttle. A program to determine spacecraft orbital decay due to perturbations is utilized for a preliminary evaluation of the orbital mechanics of the problem. Many assumptions concerning the size, shape, density, etc. of the particles are necessary for the preliminary evaluation. The results do not negate the possibility that the events observed by the radar are reentering particles originating from the shuttle.",
            "Simplified": "Se ha desarrollado un nuevo método para estimar la velocidad de los meteoros. Se ha desarrollado un nuevo método para la detección de púlsares mediante radar. El transbordador espacial Atlantis se utiliza para investigar un problema en el que las partículas del telescopio espacial Hubble ingresan a la atmósfera terrestre. El radar de observación de la Tierra de la Estación Espacial Internacional no ha detectado evidencia de una colisión entre el transbordador Columbia y la Estación Espacial Internacional."
        },
        {
            "id": 5,
            "Name": "Diseño del sistema de una mesa de medición controlada por programa y operada a distancia para la calibración del experimento Egret. Parte A: Control del programa",
            "Abstract": "The structure of the program, the five priority levels, the drive routines, the stepwise drive plan, the figure routines, meander X and y, the range of measurement table, the optimization of figure drive, the figure drive plan, dialogue routines, stack processing, the drive for the main terminal, the protocol routines, the drive for the microterminal, the drive for the experiment computer, and the main program are discussed.",
            "Simplified": "Este artículo trata sobre el diseño e implementación de un programa informático para una computadora experimental."
        },
        {
            "id": 6,
            "Name": "La evolución del proceso de rifting en la historia tectónica de la Tierra",
            "Abstract": "The continental rifting is the response of the lithosphere to the oriented tension. The distribution of viscosity in the lithosphere plays an essential role during all stages of the rifting. The viscosity is a function of the temperature, the lithostatic pressure, the rock composition, the deformation rate and other factors. The temperature is the most important factor. The vertical section of continental lithosphere of the rift zone may be divided into the following layers: the upper crust, in which brittle deformation prevails; the medialcrust, in which the role of plastic deformation increases; the lower crust, in which plastic deformation prevails; and the uppermost plastic part of the mantle overlapping asthenosphere. The depth of the boundaries in the crust layers are mainly controlled by the temperature.",
            "Simplified": "El rifting continental es la respuesta de la litosfera a la tensión orientada. Investigadores de la Universidad de California, Los Ángeles (UCLA) y la Universidad de California, Berkeley (UCB) han desarrollado una nueva forma de estudiar la corteza terrestre. La viscosidad de una roca depende de una serie de factores, incluida la presión litostática, la composición de la roca, la tasa de deformación y otros factores. La corteza terrestre está formada por tres capas: la corteza superior, la corteza media y la parte plástica de la astenosfera del manto superpuesto."
        },
        {
            "id": 7,
            "Name": "La evolución del campo de temperatura troposférica y su relación con el inicio del monzón de verano asiático",
            "Abstract": "The mean state and year-to-year variations of the tropospheric temperature fields and their relationship with the establishment of the summertime East Asian monsoon (EAM) and the Indian monsoon (INM) are studied using the NCEP reanalysis data of 15 years (1982-1996). The results show that the seasonal shift of the South Asian High in the upper troposphere and the establishment of the EAM and the INM are closely related to the seasonal warming which causes a reversal of the meridional gradient of upper tropospheric mean temperature over the monsoon regions. On the average of 15 years, the reversal time of the temperature gradient in the EAM region (INM region) is concurrent with (one pentad earlier than) the onset time of the summer monsoon. In most years of the 15-year period, the reversal of temperature gradient coincides or precedes the onset time of the summer monsoon in both the EAM region and the INM region. The results suggest an important role of thermal processes on the establishment of the Asian monsoon. The contributors to the upper tropospheric warming over the EAM region are the strong horizontal warm advection and the diabetic heating against the adiabatic cooling due to upward motion. In the INM region, strong adiabatic heating by subsidence and the diabetic heating are major warming processes against the strong horizontal cold advection related to the persistent northwestlies to the southwestern periphery of the Tibetan Plateau. It appears that the early or late establishment of the Asian summer monsoon is not directly related to the differential warming near the surface.",
            "Simplified": "Se ha investigado la influencia del máximo del sur de Asia en la troposfera superior y el establecimiento del monzón de Asia oriental (EAM) y el monzón nacional indio (INM) en la temperatura media de la troposfera superior. Investigadores de la Universidad de California, Los Ángeles (UCLA) y el Centro Nacional de Investigación Atmosférica (NCAR) en Boulder, Colorado, han investigado la influencia del CO2 atmosférico en el clima. La meseta tibetana es una de las regiones más cálidas del mundo, pero también es una de las más frías. El momento del monzón de verano asiático está influenciado por una serie de factores, que incluyen:"
        },
        {
            "id": 8,
            "Name": "Sobre la teoría de la propagación de la detonación en sistemas gaseosos",
            "Abstract": "The existing theory of detonation is critically examined. It is shown that the considerations with which the steady value of the velocity of detonation is chosen are not convincing. In connection with the problem of the process of the chemical reaction in a detonation wave, the objections raised against the conceptions of Le Chatelier and Vieille of the 19th century with regard to the ignition of the gas by the shock wave are refuted. On the basis of this concept, it is possible to give a rigorous foundation for the existing method of computing the detonation velocity. The distributions of the temperature, the pressure, and the velocity in the detonation wave front as the chemical reaction proceeds, are considered. On the assumption of the absence of losses, the pure compression of the gas in the shock wave at the start of the chemical reaction develops a temperature that is near the temperature of combustion of the given mixture at constant pressure.",
            "Simplified": "Se investigan los efectos de una onda de choque en una reacción química. En este artículo presentamos un nuevo concepto para el cálculo de la velocidad de detonación, que se basa en la idea de que la velocidad de un arma nuclear es proporcional a la velocidad a la que es detonada. Se investigan los efectos de la presión atmosférica, la temperatura y la reacción química en la detonación de un dispositivo nuclear. La temperatura de la reacción química al comienzo de la onda de choque es la misma que la temperatura del gas al comienzo de la reacción."
        },
        {
            "id": 9,
            "Name": "Efectos de la flexibilidad en la ubicación del contacto de los dientes en transmisiones de engranajes cónicos en espiral",
            "Abstract": "An analytical method to predict the shift of the contact ellipse between the meshing teeth in a spiral bevel gear set is presented in this report. The contact ellipse shift of interest is the motion of the nominal tooth contact location on each tooth from the ideal pitch point to the point of contact between the two teeth considering the elastic motions of the gears and their supporting shafts. This is the shift of the pitch point from the ideal, unloaded position on each tooth to the nominal contact location on the tooth when the gears are fully loaded. It is assumed that the major contributors of this motion are the elastic deflections of the gear shafts, the slopes of the shafts under load and the radial deflections of the four gear shaft bearings. The motions of the two pitch point locations on the pinion and the gear tooth surfaces are calculated in a FORTRAN program which also calculates the size and orientation of the Hertzian contact ellipse on the tooth faces. Based on the curvatures of the two spiral bevel gear teeth and the size of the contact ellipse, the program also predicts the basic dynamic capacity of the tooth pair. A complete numerical example is given to illustrate the use of the program.",
            "Simplified": "Un juego de engranajes cónicos en espiral es un tipo de engranaje utilizado en una variedad de aplicaciones industriales. El punto de paso es el punto en el que los engranajes están completamente cargados. Las elipses de contacto hertzianas en las superficies de los dientes del piñón y del engranaje se calculan usando un programa FORTRAN que también calcula el tamaño y la orientación de las elipses de contacto hertzianas en las caras de los dientes. Este programa predice la forma y el tamaño de las elipses de contacto entre dos dientes basándose en las curvaturas de los dos dientes del engranaje cónico en espiral y el tamaño de las elipses de contacto."
        },
        {
            "id": 10,
            "Name": "Efectos acústicos en la teoría clásica de la nucleación",
            "Abstract": "The effect of sound wave oscillations on the rate of nucleation in a parent phase can be calculated by expanding the free energy of formation of a nucleus of the second phase in powers of the acoustic pressure. Since the period of sound wave oscillation is much shorter than the time scale for nucleation, the acoustic effect can be calculated as a time average of the free energy of formation of the nucleus. The leading non-zero term in the time average of the free energy is proportional to the square of the acoustic pressure. The Young-Laplace equation for the surface tension of the nucleus can be used to link the time average of the square of the pressure in the parent phase to its time average in the nucleus of the second phase. Due to the surface tension, the pressure in the nuclear phase is higher than the pressure in the parent phase. The effect is to lower the free energy of formation of the nucleus and increase the rate of nucleation.",
            "Simplified": "La tasa de nucleación en la segunda fase de un condensado de Bose-Einstein se puede calcular expandiendo la energía libre de la segunda fase en potencias de la presión acústica. El tiempo promedio de la energía libre de una onda acústica es una función del cuadrado de la presión acústica. La ecuación de Young-Laplace para la tensión superficial del núcleo se puede utilizar para vincular el promedio temporal del cuadrado de la presión en la fase principal con su promedio temporal en el núcleo de la segunda fase. La formación de un núcleo está influenciada por una serie de factores, el más importante de los cuales es la velocidad a la que se mueven los protones y los neutrones a través del núcleo."
        },
        {
            "id": 11,
            "Name": "Un estudio de interferencia de ala de canard utilizando datos de presión experimentales a velocidades transónicas",
            "Abstract": "The canard had an exposed area of 28.0 percent of the wing reference area and was located in the chord plane of the wing or in a position 18.5 percent of the wing mean geometric chord above or below the wing chord plane. The canard leading edge sweep was 51.7 deg and the wing leading-edge sweep was 60 deg. The results indicated that the direct canard downwash effects on the wing loading are limited to the forward half of the wing directly behind the canard. The wing leading-edge vortex is located farther forward for the wing in the presence of the canard than for the wing-alone configuration. The wake, from the canard located below the wing chord plane, physically interacts with the wing inboard surface and produces a substantial loss of wing lift. For the Mach number 0.70 case, the presence of the wing increased the loading on the canard for the higher angles of attack. However, at Mach numbers of 0.95 and 1.20, the presence of the wing had the unexpected result of unloading the canard.",
            "Simplified": "Los efectos de la corriente descendente del canard sobre la carga alar se han investigado en una serie de experimentos. El vórtice del borde de ataque del ala está ubicado en el medio del ala y en presencia del canard. Para el caso del número de Mach 0,70, la presencia del ala aumentó la carga en el canard para los ángulos de ataque más altos. Un miembro del público capturó en cámara un aterrizaje canard en la Isla de Wight."
        },
        {
            "id": 12,
            "Name": "Una vista fotovoltaica de la distribución zonal media de la temperatura y el viento en la troposfera extratropical",
            "Abstract": "The dependence of the temperature and wind distribution of the zonal mean flow in the extratropical troposphere on the gradient of pontential vorticity along isentropes is examined. The extratropics here refer to the region outside the Hadley circulation. Of particular interest is whether the distribution of temperature and wind corresponding to a constant potential vorticity (PV) along isentropes resembles the observed, and the implications of PV homogenization along isentropes for the role of the tropics. With the assumption that PV is homogenized along isentropes, it is found that the temperature distribution in the extratropical troposphere may be determined by a linear, first-order partial differential equation. When the observed surface temperature distribution and tropical lapse rate are used as the boundary conditions, the solution of the equation is close to the observed temperature distribution except in the upper troposphere adjacent to the Hadley circulation, where the troposphere with no PV gradient is considerably colder. Consequently, the jet is also stronger. It is also found that the meridional distribution of the balanced zonal wind is very sensitive to the meridional distribution of the tropopause temperature. The result may suggest that the requirement of the global momentum balance has no practical role in determining the extratropical temperature distribution. The authors further investigated the sensitivity of the extratropical troposphere with constant PV along isentropes to changes in conditions at the tropical boundary (the edge of the Hadley circulation). It is found that the temperature and wind distributions in the extratropical troposphere are sensitive to the vertical distribution of PV at the tropical boundary. With a surface distribution of temperature that decreases linearly with latitude, the jet maximum occurs at the tropical boundary and moves with it. The overall pattern of wind distribution is not sensitive to the change of the position of the tropical boundary. Finally, the temperature and wind distributions of an extratropical troposphere with a finite PV gradient are calculated. It is found that the larger the isentropic PV gradient, the warmer the troposphere and the weaker the jet.",
            "Simplified": "Se investiga el papel de los isentropos en el cambio climático. La distribución de temperatura en la troposfera extratropical puede determinarse mediante una ecuación diferencial parcial de primer orden para el vórtice polar (PV). La influencia del impulso global en la distribución de temperatura extratropical ha sido examinada en un nuevo estudio. La influencia de la radiación solar (PV) en el clima de la Tierra ha sido investigada por un equipo de científicos internacionales."
        },
        {
            "id": 13,
            "Name": "Cambios a largo plazo en los espectros de edad estratosférica en el siglo XXI en el modelo químico-climático del sistema de observación de la Tierra Goddard (GEOSCCM)",
            "Abstract": "In this study we investigate the long-term variations in the stratospheric age spectra using simulations of the 21st century with the Goddard Earth Observing System Chemistry- Climate Model (GEOSCCM). Our purposes are to characterize the long-term changes in the age spectra and identify processes that cause the decrease of the mean age in a warming climate. Changes in the age spectra in the 21st century simulations are characterized by decreases in the modal age, the mean age, the spectral width, and the tail decay timescale. Our analyses show that the decrease in the mean age is caused by two processes: the acceleration of the residual circulation that increases the young air masses in the stratosphere, and the weakening of the recirculation that leads to the decrease of tail of the age spectra and the decrease of the old air masses. The weakening of the stratospheric recirculation is also strongly correlated with the increase of the residual circulation. One important result of this study is that the decrease of the tail of the age spectra makes an important contribution to the decrease of the main age. Long-term changes in the stratospheric isentropic mixing are investigated. Mixing increases in the subtropical lower stratosphere, but its impact on the age spectra is outweighed by the increase of the residual circulation. The impacts of the long-term changes in the age spectra on long-lived chemical traces are also investigated. 37 2",
            "Simplified": "La capa de ozono es una de las características más importantes de la atmósfera terrestre. La edad media de la capa de ozono estratosférico ha ido disminuyendo desde la década de 1970. El debilitamiento de la recirculación estratosférica está fuertemente correlacionado con el aumento de la circulación residual. Se investigan los efectos del cambio climático en las concentraciones de dióxido de carbono atmosférico en la atmósfera."
        },
        {
            "id": 14,
            "Name": "Evidencia de la interacción del viento IRS 16 con el gas ionizado y molecular en el centro galáctico",
            "Abstract": "We present a number of high-resolution radio images showing evidence for the dynamical interaction of the outflow arising from the IRS 16 complex with the ionized gas associated with the Northern Arm of Sgr A West, and with the northwestern segment of the circumnuclear molecular disk which engulfs the inner few parsecs of the Galactic center. We suggest that the wind disturbs the dynamics of the Northern Arm within 0.1 pc of the center, is responsible for the waviness of the arm at larger distances, and is collimated by Sgr A West and the circumnuclear disk. The waviness is discussed in terms of the Rayleigh-Taylor instability induced by the ram pressure of the wind incident on the surface of the Northern Arm. Another consequence of this interaction is the strong mid-IR polarization of the Northern Arm in the vicinity of the IRS 16 complex which is explained as a result of the ram pressure of the wind compressing the gas and the magnetic field.",
            "Simplified": "La salida de gas y polvo del centro de Sgr A West ha sido capturada por el Telescopio Espacial Hubble. Estudiamos la influencia del viento en la dinámica del Brazo Norte del Sol. La ondulación de la inestabilidad de Rayleigh-Taylor en el Brazo Norte se analiza en términos de la inestabilidad de Rayleigh-Taylor inducida por la presión del viento incidente en la superficie del Brazo Norte. El fuerte campo magnético del complejo IRS 16 interactúa con el fuerte campo magnético del Brazo Norte."
        },
        {
            "id": 15,
            "Name": "Resultados preliminares de cargas estructurales",
            "Abstract": "From a total of 351 instrumentation channels, 341 channels (97%) were in operation during the initial impact of the airplane. Both NASA seats, the energy absorbing seat and the standard seat, maintained their integrity during the impact. The floor accelerations at the seat locations were lower than the accelerations required for the energy absorbers to stroke; consequently, the energy absorbing seat did not stroke. The two seats remained firm in place during the crash and no seat attachment failures were observed. Due to the low accelerations experienced during the crash, both seats performed as standard seats. In the airplane structure, the accelerations were higher at both the point of impact in the left wing and at the forward end of the fuselage. The accelerations on the floor were higher toward the front than toward the rear and the floor accelerations on the left side were higher than on the right side at the front of the fuselage, but toward the rear they evened out.",
            "Simplified": "El diseño del asiento se basó en la idea de que el asiento debería absorber energía. La Administración Nacional de Seguridad del Tráfico en las Carreteras (NHTSA) ha publicado los resultados de una investigación sobre la muerte de una niña de 15 años que murió cuando el automóvil en el que viajaba se estrelló contra un árbol. La velocidad del impacto fue mayor en el punto de impacto en el ala izquierda que en el extremo delantero del fuselaje. Todas las imágenes tienen derechos de autor."
        },
        {
            "id": 16,
            "Name": "El flujo de un fluido comprimible que pasa por un perfil de arco circular.",
            "Abstract": "The Ackeret iteration process is utilized to obtain higher approximations than that of Prandtl and Glauert for the flow of a compressible fluid past a circular arc profile. The procedure is to expand the velocity potential in a power series of the camber coefficient. The first two terms of the development correspond to the Prandtl-Glauert approximation and yield the well-known correction to the circulation about the profile. The second approximation, involving the square of the camber coefficient, improves the velocity and pressure fields but yields no new results with regard to the circulation, since the circulation about the profile is an odd function of the camber coefficient. The third approximation, involving the cube of the camber coefficient, permits the use of higher values of the camber coefficient and furthermore yields an improvement to the Prandtl-Glauert rule with regard to the effect of compressibility on the circulation of the circular arc profile. Numerical examples with tables and graphs illustrate the results of the analysis.",
            "Simplified": "Se presentan aproximaciones de Ackeret para el flujo de un fluido comprimible que pasa por un perfil de arco circular. Los primeros tres términos del desarrollo corresponden a la aproximación de Prandtl-Glauert y dan la conocida corrección a la circulación sobre el perfil. La primera aproximación, que implica el cuadrado del coeficiente de camber, mejora los campos de velocidad y presión pero no arroja nuevos resultados sobre la circulación, ya que la circulación alrededor del perfil es una función impar del coeficiente de camber. Este artículo presenta tres nuevas aproximaciones de la regla de Prandtl-Glauert para la circulación de un perfil de arco circular."
        },
        {
            "id": 17,
            "Name": "Sobre atomización en carburadores",
            "Abstract": "The outstanding quantity of the whole atomization problem is the characteristic K, and therefore the ratio of the static pressure of the air stream with respect to the liquid to the surface tension of the liquid. The higher its value, the better the atomization. The shape of the Venturi tube plays a secondary role. The increase of section beyond the throat had best not be too abrupt.",
            "Simplified": "Este trabajo trata de la atomización de un líquido por medio de una corriente de aire. El número de protones en un átomo es una función del número de protones en el núcleo. La forma del tubo Venturi es una consideración primordial en el diseño de una planta de tratamiento de agua. Es una buena idea mantener la lengua firmemente en la garganta en todo momento."
        },
        {
            "id": 18,
            "Name": "Galileo Tierra Luna Sobrevuelo",
            "Abstract": "This video has five sections. The first is a live discussion of the information that scientists hope to gain by the Galileo flyby of the Moon. This section has no introduction. There is a great deal of the discussion about the lunar craters and lunar volcanism. There is also some discussion of the composition of the far side of the moon. The second section is a short animation that shows the final step to Jupiter with particular emphasis on the gravitational assisted velocity boost, which was planned to give the spacecraft the requisite velocity to make the trip to Jupiter. The next section is an update of the status of the flyby of the Moon, and the Earth, with an explanation of the trajectory around the earth, and the moon. A photograph of the tracking station in Canberra, Australia is included. The next section is a tour of a full-scale model of the spacecraft. The last section is a discussion with the person charged with the procurement of the instrumentation aboard the spacecraft; the importance of the lunar flyby to assist in the calibration of the instruments is discussed.",
            "Simplified": "El sitio web de BBC News está organizando una serie de eventos en vivo durante las próximas semanas. La primera sección de este video muestra el acercamiento final de la nave espacial al planeta Júpiter. Todas las fotografías tienen derechos de autor. En la segunda parte de esta serie, analizamos los instrumentos científicos a bordo del módulo de aterrizaje lunar."
        },
        {
            "id": 19,
            "Name": "La propagación de ondas de RF en un dispositivo de propulsión de plasma de espejo en tándem",
            "Abstract": "The propagation of RF waves launched in the end and the central cell of the tandem mirror propulsion device has been investigated both theoretically and experimentally. It was found that the amplitude of the wave excited in the plasma peaked while approaching the resonance, but then damped out, indicating strong absorption of the wave by the plasma. The absorption took place near the axis and the midplane of the device. The experimental results confirmed the theoretical prediction of the resonance effect. A very important discovery of this experiment was the broadening of the ICRF Fourier spectrum in the presence of the plasma.",
            "Simplified": "Se ha diseñado y probado un novedoso dispositivo de propulsión de espejos en tándem en la Universidad de California, Los Ángeles (UCLA). La absorción de una onda por un plasma de protones y neutrones se ha investigado en el Gran Colisionador de Hadrones. En este artículo presentamos los resultados de un estudio teórico del efecto de resonancia en el condensado de Bose-Einstein, que se llevó a cabo en el Instituto Tecnológico de Massachusetts (MIT). Este experimento se llevó a cabo en el Instituto Nacional de Estándares y Tecnología (NIST) en Washington, EE. UU., en presencia de un plasma."
        },
        {
            "id": 20,
            "Name": "Diseño de Software para Diseño de Elementos Finitos para Análisis Estructural",
            "Abstract": "The concepts of software engineering which allow a user of the finite element method to describe a model, to collect and to check the model data in a data base as well as to form the matrices required for a finite element calculation are examined. Next the components of the model description are conceived including the mesh tree, the topology, the configuration, the kinematic boundary conditions, the data for each element, and the loads. The possibilities for description and review of the data are considered. The concept of the segments for the modularization of the programs follows the components of the model description. The significance of the mesh tree as a globular guiding structure will be understood in view of the principle of the unity of the model, the mesh tree, and the data base. The user-friendly aspects of the software system will be summarized: the principle of language communication, the data generators, error processing, and data security.",
            "Simplified": "Se discute el método de elementos finitos y su uso en ingeniería de software. En este trabajo se modela la cinemática de un automóvil utilizando el método de los elementos finitos. La siguiente es una descripción de la modularización del software Mathematica. En este artículo, estudiamos la estructura de un árbol de malla y su relación con un modelo de la Tierra."
        },
        {
            "id": 21,
            "Name": "El movimiento convectivo y la estructura de la magnetosfera de Júpiter",
            "Abstract": "The convective motion and its relation to the electric field in the magnetosphere of Jupiter are investigated. It is shown that the electric field is induced in the Jovian ionosphere due to the corotating action of the ionospheric gases and further is communicated into the magnetosphere along the magnetic lines of force which connect between the ionosphere and the magnetosphere. This electric field drives the plasma to corotate with the planet in the magnetosphere. The distribution of the electric field and its effect on the plasma motion is estimated in the magnetosphere. The shape of the magnetosphere is then estimated considering the equilibrium condition. Discussion is given on the equilibrium plasma distribution in the magnetosphere and on the condition for the excitation of wave-particle interaction at the Io orbit.",
            "Simplified": "El movimiento convectivo del polo norte de Júpiter se ha estudiado en detalle por primera vez. El campo magnético de la Tierra es impulsado por un campo eléctrico en la atmósfera. El campo eléctrico en la magnetosfera de la Tierra se mide utilizando un espectrómetro de rayos X de alta energía. En este artículo se presenta una nueva teoría de la magnetosfera."
        },
        {
            "id": 22,
            "Name": "Modelo lunar: un núcleo compensado.",
            "Abstract": "The lunar model proposed helps to account for the offset of the center of gravity from the center of the optical figure, the moments of inertia of the Moon, the 'mascons,' the localization of the maria basins on the near side of the Moon, the igneous nature of rocks, and  the remanent magnetism. In the proposed model the Moon has a core whose center is offset from the center of the outside spheroid towards the earth. Such a core will be formed if the Moon were entirely molten at some time in its past, and on solidification was synchronous with the earth.",
            "Simplified": "Se ha propuesto por primera vez un nuevo modelo de la Luna. Científicos del Instituto Tecnológico de Massachusetts (MIT) han propuesto un nuevo modelo de la Luna. La superficie de la Luna está hecha de roca y hielo, pero el núcleo de la Luna está hecho de roca."
        },
        {
            "id": 23,
            "Name": "Generador de sesgo corporal autorregulable",
            "Abstract": "The back bias voltage on a functional circuit is controlled through a closed loop process. A delay element receives a clock pulse and produces a delay output. The delay element is advantageously constructed of the same materials as the functional circuit so that the aging and degradation of the delay element parallels the degradation of the functional circuit. As the delay element degrades, the transistor switching time increases, increasing the time delay of the delay output. An AND gate compares a clock pulse to an output pulse of the delay element, the AND output forming a control pulse. A duty cycle of the control pulse is determined by the delay time between the clock pulse and the delay element output. The control pulse is received at the input of a charge pump. The charge pump produces a back bias voltage which is then applied to the delay element and to the functional circuit. If the time delay produced by the delay element exceeds the optimal delay, the duty cycle of the control pulse is shortened, and the back bias voltage is lowered, thereby increasing the switching speed of the transistors in the delay element and reducing the time delay. If the throughput of the delay element is too fast, the duty cycle of the control pulse is lengthened, raising the back bias voltage produced by the charge pump. This, in turn, lowers the switching speed of the transistors in both the delay element and the functional circuit. The slower switching speed in the delay element increases time delay. In this manner, the switching speed of the delay element, and of the functional circuit, is maintained at a constant level over the life of the circuit.",
            "Simplified": "El voltaje de polarización inversa se controla a través de un proceso de bucle cerrado. Se utiliza una bomba de carga para controlar un elemento de retardo y un circuito funcional. Se utiliza un elemento de retardo para controlar el voltaje de polarización inversa producido por la bomba de carga. Un retraso en la velocidad de conmutación de los transistores en el elemento de retraso y el circuito funcional reduce la velocidad de conmutación de los transistores tanto en el elemento de retraso como en el circuito funcional."
        },
        {
            "id": 24,
            "Name": "La órbita de Phi Cygni medida con interferometría óptica de línea de base larga: masas de componentes y magnitudes absolutas",
            "Abstract": "The orbit of the double-lined spectroscopic binary Phi Cygni, the distance to the system, and the masses and absolute magnitudes of its components are presented via measurements with the Mar III Optical Interferometer. On the basis of a reexamination of the spectroscopic data of Rach & Herbig (1961), the values and uncertainties are adopted for the period and the projected semimajor axes from the present fit to the spectroscopic data and the values of the remaining elements from the present fit to the Mark III data. The elements of the true orbit are derived, and the masses and absolute magnitudes of the components, and the distance to the system are calculated.",
            "Simplified": "El telescopio espacial Spitzer ha captado imágenes de un sistema solar distante. Se presenta un nuevo conjunto de valores e incertidumbres para la tabla periódica. La órbita del Sol se calcula utilizando las oscilaciones del Sol y oscilaciones en el eje de rotación de la Tierra."
        }
    ]

function append() {
    let select_title = document.querySelector("#options");
    obj.forEach(json => {
        select_title.appendChild(new Option(json.Name));
    });
}

function select() {
    let select = document.querySelector("#options");
    let Optionvalue = select.options[select.selectedIndex]
    let text = Optionvalue.text;

    var title = document.getElementById("title");
    var paragraph = document.getElementById("article");

    title.innerHTML = text;
    paragraph.innerHTML = obj[select.selectedIndex]["Simplified"];

}
append();